name: Publish Release with Dynamic APK Name

on:
  push:
    tags:
      - 'v*.*.*' # 匹配类似 v1.2.0 的版本号 tag

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录以生成准确的 Changelog

      # Step 2: Set up Java Environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' # 根据项目要求更新版本
          distribution: 'temurin'
          cache: 'gradle'

      # Step 3: Prepare app.jks file
      - name: Setup app.jks
        run: |
          echo "${{ secrets.APP_JKS }}" | base64 -d > app.jks
          echo "Keystore file has been restored successfully!"

      # Step 4: Create local.properties with content to satisfy secrets plugin
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "MAPS_API_KEY=unused" >> local.properties

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: ./gradlew dependencies

      # Step 6: Build Project
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Step 7：Auto-generate Changelog
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Publish GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.github_release.outputs.changelog }} # 使用生成的 Changelog
          files: app/build/outputs/apk/release/BadgeManager_*.apk
          generate_release_notes: true # 如果没有 PR，GitHub 会尝试用 commit 生成默认备注
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的访问令牌

      # Step 9: Clean Sensitive Files (Optional)
      - name: Clean Up
        run: rm app.jks